name: SimplePlugins
version: '1.0'
main: me.Agam.simplePlugins.SimplePlugins
api-version: '1.21'
authors: [ Agam ]
description: test for practice
commands:
  msg:
    description: send a message to the player
    usage: /msg <player> <message>
  warp:
    description: teleport to a warp
    usage: /warp <id>
  setwarp:
    description: save a warp
    usage: /setwarp <id>
  deletewarp:
    description: delete a warp forever
    usage: /deletewarp <id>
    aliases: [delwarp, removewarp]
